---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# morphotype

<!-- badges: start -->
<!-- badges: end -->

The goal of morphotype is to provide a pipeline from shape data extraction to typological arrangement of pottery profiles.

## Installation

You can install the development version of morphotype from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("kafetzakid/morphotype")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(morphotype)
drawing_img = magick::image_read('~/myRpacks/morphotype/inst/extdata/SADR010324.jpg')
print(drawing_img)
img_data = morphotype::get_input(filename = 'SADR010324.jpg', trim = 10, thr = 0.9, wd = '~/myRpacks/morphotype/inst/extdata')

```

```{r notes, echo = FALSE}
# You'll still need to render `README.Rmd` regularly, to keep `README.md` up-to-date. `devtools::build_readme()` is handy for this. You could also use GitHub Actions to re-render `README.Rmd` every time you push. An example workflow can be found here: <https://github.com/r-lib/actions/tree/v1/examples>.
# 
# You can also embed plots, for example:
# 
# 
# plot(pressure)
# 
# In that case, don't forget to commit and push the resulting figure files, so they display on GitHub and CRAN.
```
